import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  guideSidebar: [
    
    'introduction',

    {
      type: 'category',
      label: "Getting started",
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'configuration',
        'buganizer'
      ]
    },
    {
      type: 'category',
      label: 'Legal',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      collapsible: true,
      items: [
        'legal/terms-of-service',
        'legal/security-policy-default'
      ]
    }

  ],

  partnerSidebar: [

    {
      type: 'category',
      label: 'Partners',
      link: {
        type: 'generated-index',
        description: 'Active partners'
    
      },
      items: [
        "partners/abc-comp",
        "partners/def-comp"
      ]
    }
  ],

  kbaseSidebar: [
    {
      type: 'category',
      label: 'Knowledge base',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        'kbase/foobar-365'
      ]
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
